articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # Article
    # Create
    path('create/', views.create, name='create'),

    # Read
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),

    # Update
    path('<int:id>/update/', views.update, name='update'),

    # Delete
    path('<int:id>/delete/', views.delete, name='delete'),

    # Comment
    # Create
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),

    # Delete
    path('<int:article_id>/commnets/<int:id>/delete/', views.comment_delete, name='comment_delete'),

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models

# 게시글(Article) 모델 정의
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)  # 생성 시간 (자동 추가)
    update_at = models.DateTimeField(auto_now=True, auto_now_add=False)  # 수정 시간 (자동 갱신)

    # comment_set: Comment 모델과의 역참조 관계 (Django에서 자동 생성)

# 댓글(Comment) 모델 정의
class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)  # 게시글과의 외래키 관계 (게시글 삭제 시 댓글도 삭제)

    # article_id: Article 모델의 id를 참조 (Django에서 자동 생성)

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta():
        model = Article
        fields = '__all__'

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        # fields는 추가할 필드 목록
        # fields = '__all__'
        # fields = ('content', )

        # exclude는 제외할 필드 목록
        exclude = ('article', )

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, CommentForm
from .models import Article, Comment

# 게시글 생성 함수
def create(request):
    if request.method == 'POST':  # POST 요청일 경우
        form = ArticleForm(request.POST)  # 전달받은 데이터를 폼에 넣기기
        if form.is_valid():  # 폼 데이터가 유효한지 검증
            form.save()  # 유효하다면 저장
            return redirect('articles:index')  # 저장 후 index 페이지로 리다이렉트
    else:
        form = ArticleForm()  # 빈 폼 생성

    context = {
        'form': form,  # 템플릿에 전달할 폼 객체
    }
    return render(request, 'create.html', context)  # create.html 렌더링

# 게시글 목록 조회 함수
def index(request):
    articles = Article.objects.all()  # 모든 게시글 조회

    context = {
        'articles': articles,  # 템플릿에 전달할 게시글 리스트
    }

    return render(request, 'index.html', context)  # index.html 렌더링

# 게시글 상세 조회 함수
def detail(request, id):
    article = Article.objects.get(id=id)  # 특정 id의 게시글 조회
    form = CommentForm()  # 댓글 작성 폼 생성
    context = {
        'article': article,  # 템플릿에 전달할 게시글 객체
        'form': form,  # 템플릿에 전달할 댓글 폼
    }

    return render(request, 'detail.html', context)  # detail.html 렌더링

# 게시글 수정 함수
def update(request, id):
    article = Article.objects.get(id=id)  # 특정 id의 게시글 조회
    if request.method == 'POST':  # POST 요청일 경우
        form = ArticleForm(request.POST, instance=article)  # 기존 게시글 데이터를 폼에 넣기
        if form.is_valid():  # 폼 데이터가 유효한지 검증
            form.save()  # 유효하다면 저장
            return redirect('articles:detail', id=id)  # 저장 후 상세 페이지로 리다이렉트
    else:
        form = ArticleForm(instance=article)  # 기존 게시글 데이터를 폼에 넣기기

    context = {
        'form': form,  # 템플릿에 전달할 폼 객체
    }
    return render(request, 'update.html', context)  # update.html 렌더링

# 게시글 삭제 함수
def delete(request, id):
    article = Article.objects.get(id=id)  # 특정 id의 게시글 조회
    article.delete()  # 게시글 삭제
    return redirect('articles:index')  # 삭제 후 index 페이지로 리다이렉트

# 댓글 생성 함수
def comment_create(request, article_id):
    if request.method == 'POST':  # POST 요청일 경우
        form = CommentForm(request.POST)  # 전달받은 데이터를 폼에 바인딩
        if form.is_valid():  # 폼 데이터가 유효한지 검증
            comment = form.save(commit=False)  # 데이터 저장 전 객체 반환
            article = Article.objects.get(id=article_id)  # 댓글이 달릴 게시글 조회
            comment.article = article  # 댓글에 게시글 연결
            comment.save()  # 댓글 저장
            
        return redirect('articles:detail', id=article_id)  # 저장 후 상세 페이지로 리다이렉트
    else:
        return redirect('articles:index')  # index 페이지로 리다이렉트

# 댓글 삭제 함수
def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)  # 특정 id의 댓글 조회
    comment.delete()  # 댓글 삭제

    return redirect('articles:detail', id=article_id)  # 삭제 후 상세 페이지로 리다이렉트

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{article.title}}</h1>
    <p>{{article.content}}</p>
    <p>{{article.created_at}}</p>
    <p>{{article.update_at}}</p>

    <a href="{% url 'articles:update' article.id %}">UPDATE</a>
    <a href="{% url 'articles:delete' article.id %}">DELETE</a>

    <hr>

    <form action="{% url 'articles:comment_create' article.id %}" method='POST'>
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

    <hr>
    
    {% for comment in article.comment_set.all %}
        <li>{{comment.content}}</li>
        <a href="{% url 'articles:comment_delete' article.id comment.id %}">DELETE</a>
    {% endfor %}
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'articles:create' %}">CREATE</a>
    {% for article in articles %}
        <h1>{{article.title}}</h1>
        <a href="{% url 'articles:detail' article.id %}">DETAIL</a>
    {% endfor %}

{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>